Use short array syntax & fix typos.
airbrake/phpbrake pull request #42
Opened 2016-11-09 18:42 UTC by bcrowe

Using short array syntax will make things a little more copy/paste friendly for the majority's preferences.

2016-11-09 20:50 UTC, kyrylo commented on README.md
>      'projectKey' => 'abcdefg', // FIX ME
Unwanted comma.

2016-11-09 20:53 UTC, kyrylo requested changes
👍  Needs one tiny change.

2016-11-09 23:30 UTC, bcrowe commented
@kyrylo Fixed.

2016-11-10 00:11 UTC, kyrylo approved these changes

2016-11-10 00:11 UTC, merged